aea_version: 0.1.10
agent_name: agent_submarine
authors: 'Talia Kimber, Maxime Gagnebin, Alessandro Ricottoni'
connections:
- local
- oef
- stub
default_connection: oef
description: ''
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
- private_key_path:
    ledger: default
    path: default_private_key.pem
- private_key_path:
    ledger: fetchai
    path: fet_private_key.txt
- private_key_path:
    ledger: ethereum
    path: eth_private_key.txt
protocols:
- default
registry_path: ../packages
skills:
- get_data
- error
url: ''
version: v1
